import { useEffect, useState } from "react";
import { getLanguage, translations } from "../translations";

const numberWords = {
  en: {
    1: "one",
    2: "two",
    3: "three",
    4: "four",
    5: "five",
    6: "six",
    7: "seven",
    8: "eight",
    9: "nine",
    10: "ten",
    11: "eleven",
    12: "twelve",
    15: "quarter",
    20: "twenty",
    25: "twenty-five"
  },
  de: {
    1: "eins",
    2: "zwei",
    3: "drei",
    4: "vier",
    5: "fünf",
    6: "sechs",
    7: "sieben",
    8: "acht",
    9: "neun",
    10: "zehn",
    11: "elf",
    12: "zwölf",
    15: "Viertel",
    20: "zwanzig",
    25: "fünfundzwanzig"
  },
  fr: {
    1: "une",
    2: "deux",
    3: "trois",
    4: "quatre",
    5: "cinq",
    6: "six",
    7: "sept",
    8: "huit",
    9: "neuf",
    10: "dix",
    11: "onze",
    12: "douze",
    15: "quart",
    20: "vingt",
    25: "vingt-cinq"
  },
  it: {
    1: "l’una",
    2: "due",
    3: "tre",
    4: "quattro",
    5: "cinque",
    6: "sei",
    7: "sette",
    8: "otto",
    9: "nove",
    10: "dieci",
    11: "undici",
    12: "dodici",
    15: "un quarto",
    20: "venti",
    25: "venticinque"
  },
  es: {
    1: "la una",
    2: "las dos",
    3: "las tres",
    4: "las cuatro",
    5: "las cinco",
    6: "las seis",
    7: "las siete",
    8: "las ocho",
    9: "las nueve",
    10: "las diez",
    11: "las once",
    12: "las doce",
    15: "cuarto",
    20: "veinte",
    25: "veinticinco"
  },
  pt: {
    1: "uma",
    2: "duas",
    3: "três",
    4: "quatro",
    5: "cinco",
    6: "seis",
    7: "sete",
    8: "oito",
    9: "nove",
    10: "dez",
    11: "onze",
    12: "doze",
    15: "um quarto",
    20: "vinte",
    25: "vinte e cinco"
  }
};
